<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { getInstanceByDom, init, use } from 'echarts/core'
import { LineChart } from 'echarts/charts'
import { GridComponent, TooltipComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { api, localTime, money, percent } from '../api'
use([LineChart, GridComponent, TooltipComponent, CanvasRenderer])
const availability=ref<any[]>([]),jobs=ref<any[]>([]),versions=ref<any[]>([]),selected=ref<any>(),submitting=ref(false)
const form=reactive({dates:[] as string[],starting_equity:'100000',config_version:undefined as number|undefined})
const completeDates=computed(()=>availability.value.filter(x=>x.bars).map(x=>x.date))
const chartRef=ref<HTMLElement>(), dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
let timer:number
async function load(){const [a,j,v]=await Promise.all([api.get('/market-data/availability'),api.get('/backtests'),api.get('/config/versions')]);availability.value=a.data;jobs.value=j.data;versions.value=v.data;if(selected.value)selected.value=jobs.value.find(x=>x.id===selected.value.id)||selected.value}
async function submit(){if(form.dates.length!==2){ElMessage.warning('请选择回测日期范围');return}submitting.value=true;try{selected.value=(await api.post('/backtests',{start_date:form.dates[0],end_date:form.dates[1],starting_equity:form.starting_equity,config_version:form.config_version})).data;await load();ElMessage.success('回测任务已进入队列')}finally{submitting.value=false}}
async function cancel(job:any){await api.delete(`/backtests/${job.id}`);await load()}
onMounted(async()=>{await load();timer=window.setInterval(load,2500)});onBeforeUnmount(()=>clearInterval(timer))
watch(()=>selected.value?.result?.equity_curve,async curve=>{if(!curve?.length)return;await nextTick();if(!chartRef.value)return;const chart=getInstanceByDom(chartRef.value)||init(chartRef.value);chart.setOption({grid:{left:55,right:20,top:20,bottom:35},tooltip:{trigger:'axis'},xAxis:{type:'category',data:curve.map((x:any)=>new Date(x.time).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})),axisLabel:{color:'#7890ad'}},yAxis:{type:'value',scale:true,axisLabel:{color:'#7890ad'}},series:[{type:'line',smooth:true,showSymbol:false,data:curve.map((x:any)=>Number(x.equity)),lineStyle:{color:'#2dd4bf',width:2},areaStyle:{color:'rgba(45,212,191,.1)'}}]});},{deep:true})
</script>
<template>
  <div class="panel"><div class="panel-title"><h2>创建回测</h2><span>单任务 FIFO 队列</span></div><div class="toolbar"><el-date-picker v-model="form.dates" type="daterange" value-format="YYYY-MM-DD" :disabled-date="(d: Date)=>!completeDates.includes(dateKey(d))" start-placeholder="开始日期" end-placeholder="结束日期"/><el-input v-model="form.starting_equity" placeholder="初始权益" style="width:150px"><template #prepend>$</template></el-input><el-select v-model="form.config_version" clearable placeholder="当前环境参数" style="width:180px"><el-option v-for="v in versions" :key="v.version" :label="`参数版本 v${v.version}`" :value="v.version"/></el-select><el-button type="primary" :loading="submitting" @click="submit">开始回测</el-button></div><div class="data-strip"><span v-for="item in availability.slice(0,12)" :key="item.date" :title="`${item.date} K线:${item.bars} 期权:${item.options} VIX:${item.volatility_intraday}`" :class="{complete:item.bars&&item.options&&item.volatility_intraday}">{{ item.date.slice(5) }}</span></div></div>
  <div class="grid two" style="margin-top:18px"><div class="panel"><div class="panel-title"><h2>任务队列</h2><span>{{ jobs.length }} 条历史</span></div><el-table :data="jobs" @row-click="(r: any)=>selected=r"><el-table-column label="时间" min-width="150"><template #default="s">{{ localTime(s.row.created_at) }}</template></el-table-column><el-table-column label="范围" min-width="150"><template #default="s">{{ s.row.request.start_date }} → {{ s.row.request.end_date }}</template></el-table-column><el-table-column prop="status" label="状态" width="105"/><el-table-column label="进度" width="120"><template #default="s"><el-progress :percentage="s.row.progress" :show-text="false"/></template></el-table-column><el-table-column width="80"><template #default="s"><el-button v-if="['queued','running'].includes(s.row.status)" link type="danger" @click.stop="cancel(s.row)">取消</el-button></template></el-table-column></el-table></div>
    <div class="panel"><div class="panel-title"><h2>回测结果</h2><span>{{ selected?.id?.slice(0,8)||'未选择' }}</span></div><template v-if="selected?.result"><div class="grid metrics result-grid"><div class="metric"><label>净收益</label><strong :class="Number(selected.result.net_pnl)>=0?'positive':'negative'">{{ money(selected.result.net_pnl) }}</strong></div><div class="metric"><label>收益率</label><strong>{{ percent(selected.result.return_rate) }}</strong></div><div class="metric"><label>胜率</label><strong>{{ percent(selected.result.win_rate) }}</strong></div><div class="metric"><label>最大回撤</label><strong class="negative">{{ money(selected.result.max_drawdown) }}</strong></div></div><div ref="chartRef" style="height:210px;margin-top:16px"></div><div class="kv" style="margin-top:20px"><div><label>期权数据完整</label><b>{{ selected.result.option_data_complete?'是':'否' }}</b></div><div><label>VIX 数据完整</label><b>{{ selected.result.volatility_data_complete?'是':'否' }}</b></div><div><label>信号数量</label><b>{{ selected.result.signals }}</b></div><div><label>拒绝原因</label><b>{{ JSON.stringify(selected.result.rejected) }}</b></div></div></template><div v-else-if="selected?.error" class="empty negative">{{ selected.error }}</div><div v-else class="empty">{{ selected ? `任务${selected.status==='running'?'运行中':'等待执行'}` : '从队列选择一个任务' }}</div></div></div>
  <div v-if="selected?.result?.trades?.length" class="panel" style="margin-top:18px"><div class="panel-title"><h2>回测交易明细</h2><span>{{ selected.result.trades.length }} 笔</span></div><el-table :data="selected.result.trades"><el-table-column prop="symbol" label="合约"/><el-table-column prop="direction" label="方向"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="entry_price" label="入场"/><el-table-column prop="exit_price" label="出场"/><el-table-column prop="pnl" label="盈亏"/><el-table-column prop="reason" label="原因"/></el-table></div>
</template>
<style scoped>.data-strip{display:flex;gap:6px;flex-wrap:wrap}.data-strip span{font:10px Consolas;color:#68809b;background:#091523;padding:5px 7px;border-radius:4px}.data-strip span.complete{color:var(--green);border:1px solid #185842}.result-grid{grid-template-columns:repeat(2,1fr)!important}.result-grid strong{font-size:20px}</style>
