<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, localTime, money, percent } from '../api'
const reports=ref<any[]>([]), selected=ref<any>(), loading=ref(false)
async function loadList(){reports.value=(await api.get('/reports')).data;if(reports.value.length) await select(reports.value[0].date)}
async function select(value:string){loading.value=true;try{selected.value=(await api.get(`/reports/${value}`)).data}finally{loading.value=false}}
onMounted(loadList)
</script>
<template>
  <div class="grid two">
    <div class="panel" style="max-width:300px"><div class="panel-title"><h2>历史日报</h2><span>{{ reports.length }} 日</span></div><div v-if="!reports.length" class="empty">暂无日报</div><div v-for="item in reports" :key="item.date" class="report-item" :class="{active:selected?.trading_date===item.date}" @click="select(item.date)"><b>{{ item.date }}</b><span :class="Number(item.metrics?.net_pnl)>=0?'positive':'negative'">{{ money(item.metrics?.net_pnl) }}</span></div></div>
    <div v-loading="loading" class="panel"><template v-if="selected"><div class="panel-title"><h2>{{ selected.trading_date }} 交易日报</h2><span>生成于 {{ localTime(selected.generated_at) }}</span></div><div class="grid metrics" style="grid-template-columns:repeat(4,1fr)"><div class="metric"><label>净盈亏</label><strong :class="Number(selected.metrics.net_pnl)>=0?'positive':'negative'">{{ money(selected.metrics.net_pnl) }}</strong></div><div class="metric"><label>胜率</label><strong>{{ percent(selected.metrics.win_rate) }}</strong></div><div class="metric"><label>交易数</label><strong>{{ selected.metrics.trade_count }}</strong></div><div class="metric"><label>最大回撤</label><strong class="negative">{{ money(selected.metrics.max_intraday_drawdown) }}</strong></div></div><img :src="`/api/v1/reports/${selected.trading_date}/chart?t=${encodeURIComponent(selected.generated_at||'')}`" class="report-chart"/><h3>交易记录</h3><el-table :data="selected.trades"><el-table-column prop="symbol" label="合约"/><el-table-column prop="direction" label="方向"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="entry_price" label="入场"/><el-table-column prop="exit_price" label="出场"/><el-table-column prop="pnl" label="盈亏"/></el-table><h3>分析建议</h3><ul><li v-for="item in selected.suggestions" :key="item">{{ item }}</li></ul><div class="kv"><div><label>被拒绝信号</label><b>{{ selected.rejected_signals?.length || 0 }}</b></div><div><label>系统事件</label><b>{{ selected.system_events?.length || 0 }}</b></div><div><label>期权数据完整</label><b>{{ selected.option_backtest_complete?'是':'否' }}</b></div><div><label>数据质量</label><b>{{ JSON.stringify(selected.data_quality||{}) }}</b></div></div></template><div v-else class="empty">选择一份日报查看详情</div></div>
  </div>
</template>
<style scoped>.report-item{display:flex;justify-content:space-between;padding:13px 12px;margin-bottom:6px;border-radius:7px;color:#a9bdd5;cursor:pointer}.report-item:hover,.report-item.active{background:#142840;color:white}.report-chart{width:100%;margin:24px 0 10px;background:#f7f9fc;border-radius:8px}h3{font-size:13px;margin-top:24px}li{color:#a9bdd5;margin:8px 0}</style>
